// makefile-gen.c - Generate Makefile from C source analysis

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <ctype.h>
#include <glob.h>

#define MAX_LIBS 20
#define MAX_LINE 256

typedef struct {
    char name[64];
    int count;
} Library;

Library libs[MAX_LIBS];
int lib_count = 0;

// Check if library exists in lib directory
int library_exists(const char *lib_name) {
    char pattern[256];
    snprintf(pattern, sizeof(pattern), "../../lib/lib%s_*.a", lib_name);
    
    glob_t globbuf;
    int result = glob(pattern, 0, NULL, &globbuf);
    globfree(&globbuf);
    
    return (result == 0);  // Returns 1 if at least one matching file found
}

// Extract library name from header - handle both "" and <>
void extract_lib_name(const char *line, char *lib_name) {
    const char *start = strchr(line, '"');
    if (!start) {
        // Try angle brackets
        start = strchr(line, '<');
    }
    if (!start) return;
    start++;
    
    const char *end = strchr(start, '.');
    if (!end) return;
    
    int len = end - start;
    if (len > 0 && len < 64) {
        strncpy(lib_name, start, len);
        lib_name[len] = '\0';
    }
}

// Add library if not already in list
void add_library(const char *lib_name) {
    // Skip avr/ and sys/ system headers
    if (strncmp(lib_name, "avr/", 4) == 0 || 
        strncmp(lib_name, "sys/", 4) == 0 ||
        strncmp(lib_name, "util/", 5) == 0) {
        return;
    }
    
    // Skip standard C headers
    if (strcmp(lib_name, "stdio") == 0 || 
        strcmp(lib_name, "stdlib") == 0 ||
        strcmp(lib_name, "string") == 0 ||
        strcmp(lib_name, "stdint") == 0 ||
        strcmp(lib_name, "stdbool") == 0) {
        return;
    }
    
    // Check if already exists
    for (int i = 0; i < lib_count; i++) {
        if (strcmp(libs[i].name, lib_name) == 0) {
            libs[i].count++;
            return;
        }
    }
    
    // Add new library
    if (lib_count < MAX_LIBS) {
        strcpy(libs[lib_count].name, lib_name);
        libs[lib_count].count = 1;
        lib_count++;
    }
}

// Scan C file for includes
void scan_file(const char *filename) {
    FILE *f = fopen(filename, "r");
    if (!f) return;
    
    char line[MAX_LINE];
    while (fgets(line, sizeof(line), f)) {
        if (strncmp(line, "#include", 8) == 0) {
            // Accept both "" and <>
            if (strchr(line, '"') || strchr(line, '<')) {
                char lib_name[64] = {0};
                extract_lib_name(line, lib_name);
                if (lib_name[0]) {
                    add_library(lib_name);
                }
            }
        }
    }
    
    fclose(f);
}


// Check if uart library is needed
int has_uart_lib(void) {
    for (int i = 0; i < lib_count; i++) {
        if (strstr(libs[i].name, "uart") != NULL) {
            return 1;
        }
    }
    return 0;
}

/*
void generate_makefile(const char *target, const char *mcu_list) {
    printf("# This Makefile was automatically generated by makefile-gen\n");
    printf("# Edit it to adapt to your needs (library order, MCU list, etc.)\n\n");
    
    printf("include ../common.mk\n\n");
    printf("TARGET = %s\n", target);
    printf("SRC = $(TARGET).c\n");
    printf("MCUS = %s\n", mcu_list);
    
    printf("LIBS =");
    for (int i = 0; i < lib_count; i++) {
        if (strstr(libs[i].name, "uart") == NULL) {
            // Only add if library actually exists
            if (library_exists(libs[i].name)) {
                printf(" -l%s_$(MCU)", libs[i].name);
            }
        }
    }
    printf("\n\n");
    
    if (has_uart_lib()) {
        printf("# Conditional UART library\n");
        printf("ifneq ($(findstring tiny,$(MCU)),)\n");
        printf("    LIBS += -luart-tiny_$(MCU)\n");
        printf("else\n");
        printf("    LIBS += -luart-mega_$(MCU)\n");
        printf("endif\n\n");
    }
    
    printf("include ../project.mk\n");
}
*/

void generate_makefile(const char *target, const char *mcu_list, char c_files[][64], int c_file_count) {
    printf("# This Makefile was automatically generated by makefile-gen\n");
    printf("# Edit it to adapt to your needs (library order, MCU list, etc.)\n\n");
    
    printf("include ../common.mk\n\n");
    printf("TARGET = %s\n", target);
    
    // Multiple source files
    printf("SRC = ");
    for (int i = 0; i < c_file_count; i++) {
        printf("%s", c_files[i]);
        if (i < c_file_count - 1) printf(" ");
    }
    printf("\n");
    
    printf("MCUS = %s\n", mcu_list);
    
    printf("LIBS =");
    for (int i = 0; i < lib_count; i++) {
        if (strstr(libs[i].name, "uart") == NULL) {
            if (library_exists(libs[i].name)) {
                printf(" -l%s_$(MCU)", libs[i].name);
            }
        }
    }
    printf("\n\n");
    
    if (has_uart_lib()) {
        printf("# Conditional UART library\n");
        printf("ifneq ($(findstring tiny,$(MCU)),)\n");
        printf("    LIBS += -luart-tiny_$(MCU)\n");
        printf("else\n");
        printf("    LIBS += -luart-mega_$(MCU)\n");
        printf("endif\n\n");
    }
    
    printf("include ../project.mk\n");
}

/*
int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <project.c> \"MCU_list\"\n", argv[0]);
        fprintf(stderr, "Example: %s diskbrowser.c \"atmega1284p atmega2560\"\n", argv[0]);
        return 1;
    }
    
    // Extract target name from filename
    char target[64];
    const char *basename = strrchr(argv[1], '/');
    basename = basename ? basename + 1 : argv[1];
    
    strncpy(target, basename, sizeof(target) - 1);
    char *dot = strrchr(target, '.');
    if (dot) *dot = '\0';
    
    // Scan the file
    scan_file(argv[1]);
    
    // Generate Makefile
    generate_makefile(target, argv[2]);

    // Warning message to stderr (won't go into the Makefile)
    fprintf(stderr, "\nMakefile generated successfully!\n");
    fprintf(stderr, "Please review and edit the Makefile to:\n");
    fprintf(stderr, "  - Adjust library order if needed\n");
    fprintf(stderr, "  - Add or remove MCUs from the MCUS list\n");
    fprintf(stderr, "  - Verify all required libraries are included\n\n");
    
    return 0;
}
*/

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <project.c> \"MCU_list\"\n", argv[0]);
        fprintf(stderr, "Example: %s diskbrowser.c \"atmega1284p atmega2560\"\n", argv[0]);
        return 1;
    }
    
    // Extract target name and directory from filename
    char target[64];
    char dir[256] = ".";
    
    const char *slash = strrchr(argv[1], '/');
    if (slash) {
        int dir_len = slash - argv[1];
        strncpy(dir, argv[1], dir_len);
        dir[dir_len] = '\0';
        slash++;
    } else {
        slash = argv[1];
    }
    
    strncpy(target, slash, sizeof(target) - 1);
    char *dot = strrchr(target, '.');
    if (dot) *dot = '\0';
    
    // Scan all .c files in the directory
    DIR *d = opendir(dir);
    if (!d) {
        fprintf(stderr, "Cannot open directory: %s\n", dir);
        return 1;
    }
    
    char c_files[MAX_LIBS][64];
    int c_file_count = 0;
    
    struct dirent *entry;
    while ((entry = readdir(d)) != NULL && c_file_count < MAX_LIBS) {
        if (strstr(entry->d_name, ".c") && 
            entry->d_name[strlen(entry->d_name) - 2] == '.') {
            strcpy(c_files[c_file_count++], entry->d_name);
            
            // Scan this file for includes
            char filepath[512];
            snprintf(filepath, sizeof(filepath), "%s/%s", dir, entry->d_name);
            scan_file(filepath);
        }
    }
    closedir(d);
    
    // Generate Makefile
    generate_makefile(target, argv[2], c_files, c_file_count);
    
    // Warning message
    fprintf(stderr, "\nMakefile generated successfully!\n");
    fprintf(stderr, "Please review and edit the Makefile to:\n");
    fprintf(stderr, "  - Adjust library order if needed\n");
    fprintf(stderr, "  - Add or remove MCUs from the MCUS list\n");
    fprintf(stderr, "  - Verify all required libraries are included\n\n");
    
    return 0;
}
