MCU = atmega328p
F_CPU = 16000000UL
CC = avr-gcc
OBJCOPY = avr-objcopy
CFLAGS = -Wall -Os -mmcu=$(MCU) -DF_CPU=$(F_CPU)

program.hex: program.elf
	$(OBJCOPY) -O ihex $< $@

program.elf: main.c
	$(CC) $(CFLAGS) -o $@ $

flash: program.hex
	avrdude -c arduino -p $(MCU) -P /dev/ttyUSB0 -b 115200 -U flash:w:$

clean:
	rm -f *.hex *.elf *.o
	